# These are supported funding model platforms

github: ['kennedy-ex', 'riz-ex', 'aryazakaria01', 'FeriEXP']
community_bridge: kennedy-project
custom: ['https://t.me/CryptooLounge', 'https://t.me/TobiCryptoLounge_Bot']
